# Numpy Crash Course

In [ ]:
'''
OBS:
# Clears all variable values previously set
# from IPython import get_ipython
# get_ipython().magic('reset -sf')
'''

In [ ]:
'''import libraries'''
# Provides ways to work with large multidimensional arrays
import numpy as np 
# Allows for further data manipulation and analysis
import pandas as pd

# In Anaconda -> Environments -> Not Installed -> pandas-datareader -> Apply
from pandas_datareader import data as web # Reads stock data 
import matplotlib.pyplot as plt # Plotting
import matplotlib.dates as mdates # Styling dates
%matplotlib inline

#Ploty
import cufflinks as cf
import plotly.express as px
import plotly.graph_objects as go

# Ignore warnings
import warnings
warnings.simplefilter("ignore")

In [3]:
# numpy array
list1 = [1, 2, 3, 4, 5]
npal = np.array(list1)
npal


array([1, 2, 3, 4, 5])

In [10]:
# array from 0 to 7
npa2 = np.arange(0,8)
npa2

npa3 = np.arange(8)
print(npa2)
print(npa3)

[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]


In [11]:
# defining a step
npa4 = np.arange(0,8,2)
npa4

array([0, 2, 4, 6])

### Matrices

In [12]:
# Create a 4 row matrix with 3 columns with all having a value of 1

mat1 = np.ones((4,3))
mat1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# Now 4 rows 3 col matrix with all having a value of 0

mat0 = np.zeros((4,3))
mat0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Random matrices

In [14]:
# random values between 0 and 50 in a 4x3 matrix

matran = np.random.randint(0,50,(4,3))
matran

array([[45, 28, 40],
       [21, 19, 18],
       [47, 48,  4],
       [26, 33, 21]], dtype=int32)

### Generate Defined Number of Values in Range

In [18]:
# Generate 10 equally distanced values between 1 and 10
mat4 = np.linspace(0,10,10)
mat4

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

### Reshaped Arrays